//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int id { get; set; }
        public string Class { get; set; }
        public string CarType { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Color { get; set; }
        public Nullable<int> Doors { get; set; }
        public Nullable<int> KMs { get; set; }
        public Nullable<int> LicensePlate { get; set; }
        public Nullable<System.DateTime> DateOnRoad { get; set; }
        public Nullable<System.DateTime> NextServiceDate { get; set; }
        public Nullable<int> NextServiceKMS { get; set; }
        public Nullable<bool> StatusInService { get; set; }
        public Nullable<bool> StatusRented { get; set; }
        public Nullable<int> CustID { get; set; }
        public string Notes { get; set; }
    }
}
