//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int id { get; set; }
        public string Class { get; set; }
        public Nullable<int> FreeKMs { get; set; }
        public Nullable<decimal> HighSeasonDay { get; set; }
        public Nullable<decimal> LowSeasonDay { get; set; }
        public Nullable<decimal> HighSeasonKM { get; set; }
        public Nullable<decimal> LowSeasonKM { get; set; }
        public string Example { get; set; }
        public string ImageSource { get; set; }
    }
}
