//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int id { get; set; }
        public Nullable<int> CustID { get; set; }
        public Nullable<int> CarID { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Notes { get; set; }
        public Nullable<int> MileageOut { get; set; }
        public Nullable<int> MileageIn { get; set; }
    }
}
